### ISSUE TITLE
Remove dependency of pelias-config

### ISSUE THREAD

**Issue by ryanramage** [pelias/esclient#3]
I would suggest that using pelias-config is counter intuitive to the end user. I expected that the config I pass esclient is passed directly to the elasticsearch client. Here is what I would propose:

```
module.exports = function( config ){

  // Create new esclient with settings
  var client = new elasticsearch.Client( config || {} );
```

and then a someone who wants to use pelias-config, would just do the following:

```
  var settings = require('pelias-config').generate();
  var esclient = require('pelias-esclient')(settings);
```

This seems a much cleaner separation to how I would expect as a consumer of esclient.

**Comment by missinglink** [comment]
I'm assigning this ticket to myself for next week, the result will likely be a cleaning up and documenting `pelias/dbclient` and deprecating `pelias/esclient`.

In the process, I'd love `dbclient` to become a general purpose streaming elasticsearch indexer and so +1 for removing `pelias/*` specific dependencies.

**Comment by missinglink** [comment]
closing in favour of https://github.com/geopipes/elasticsearch-indexer/issues/1
